-- ============================================================================
-- DANA Games Price Intelligence - Supabase schema
-- Run this file ONCE in the Supabase SQL Editor (as the postgres role),
-- then run seed.sql.
--
-- Access model:
--   anon            -> no access
--   authenticated   -> read everything; config writes restricted to admins
--                      via Row Level Security + public.is_admin()
--   service_role    -> full access (GitHub Actions scraper, secret key)
-- ============================================================================

create extension if not exists pgcrypto;

-- ---------------------------------------------------------------------------
-- user_profiles: role per dashboard user; auto-created on signup.
-- The FIRST user to sign up becomes 'admin' automatically.
-- (Created before is_admin() because that function reads this table.)
-- ---------------------------------------------------------------------------
create table if not exists public.user_profiles (
    id          uuid primary key references auth.users(id) on delete cascade,
    email       text not null,
    role        text not null default 'viewer' check (role in ('admin', 'viewer')),
    created_at  timestamptz not null default now()
);

-- ---------------------------------------------------------------------------
-- Admin helper (security definer to avoid RLS recursion on user_profiles)
-- ---------------------------------------------------------------------------
create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
    select exists (
        select 1
        from public.user_profiles
        where id = auth.uid()
          and role = 'admin'
    );
$$;

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
    v_role text;
begin
    select case
        when not exists (select 1 from public.user_profiles) then 'admin'
        else 'viewer'
    end into v_role;

    insert into public.user_profiles (id, email, role)
    values (new.id, coalesce(new.email, ''), v_role);

    return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
    after insert on auth.users
    for each row execute function public.handle_new_user();

-- ---------------------------------------------------------------------------
-- updated_at trigger
-- ---------------------------------------------------------------------------
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
    new.updated_at = now();
    return new;
end;
$$;

-- ---------------------------------------------------------------------------
-- games: monitored titles; dana_url is the DANA catalog page used for
-- automatic SKU discovery.
-- ---------------------------------------------------------------------------
create table if not exists public.games (
    id          bigint generated by default as identity primary key,
    slug        text not null unique,
    name        text not null,
    dana_url    text,
    active      boolean not null default true,
    created_at  timestamptz not null default now(),
    updated_at  timestamptz not null default now()
);

-- ---------------------------------------------------------------------------
-- game_skus: canonical DANA package catalog (auto-populated by the scraper).
-- effective_units = base_units + bonus_units (stored generated column).
-- ---------------------------------------------------------------------------
create table if not exists public.game_skus (
    id                  bigint generated by default as identity primary key,
    game_id             bigint not null references public.games(id) on delete cascade,
    sku_code            text not null,
    display_name        text not null,
    base_units          integer not null check (base_units >= 0),
    bonus_units         integer not null default 0 check (bonus_units >= 0),
    effective_units     integer generated always as (base_units + bonus_units) stored,
    dana_current_price  numeric(12, 2),
    active              boolean not null default true,
    created_at          timestamptz not null default now(),
    updated_at          timestamptz not null default now(),
    unique (game_id, sku_code)
);

-- ---------------------------------------------------------------------------
-- sources: DANA itself plus competitor platforms.
-- ---------------------------------------------------------------------------
create table if not exists public.sources (
    id          bigint generated by default as identity primary key,
    slug        text not null unique,
    name        text not null,
    source_type text not null default 'competitor' check (source_type in ('dana', 'competitor')),
    base_url    text,
    enabled     boolean not null default true,
    notes       text,
    created_at  timestamptz not null default now(),
    updated_at  timestamptz not null default now()
);

-- ---------------------------------------------------------------------------
-- source_sku_mappings: one competitor product page per (source, game).
-- sku_id is a MANUAL mapping override; null = automatic matching by
-- game + effective units. Selectors are optional overrides.
-- ---------------------------------------------------------------------------
create table if not exists public.source_sku_mappings (
    id               bigint generated by default as identity primary key,
    source_id        bigint not null references public.sources(id) on delete cascade,
    game_id          bigint not null references public.games(id) on delete cascade,
    sku_id           bigint references public.game_skus(id) on delete set null,
    product_url      text not null,
    product_label    text,
    price_selector   text,
    units_selector   text,
    enabled          boolean not null default true,
    requires_auth    boolean not null default false,
    last_scrape_status text check (last_scrape_status in ('success', 'failed')),
    last_scrape_at   timestamptz,
    last_error       text,
    created_at       timestamptz not null default now(),
    updated_at       timestamptz not null default now(),
    unique (source_id, game_id, product_url)
);

-- ---------------------------------------------------------------------------
-- price_logs: every scrape attempt (success AND failure). Never store a
-- price of zero for missing data - use scrape_status = 'failed'.
-- ---------------------------------------------------------------------------
create table if not exists public.price_logs (
    id                   bigint generated by default as identity primary key,
    mapping_id           bigint references public.source_sku_mappings(id) on delete set null,
    sku_id               bigint references public.game_skus(id) on delete set null,
    game_id              bigint references public.games(id) on delete cascade,
    source_id            bigint not null references public.sources(id) on delete cascade,
    product_name         text,
    total_price          numeric(12, 2),
    currency             text not null default 'IDR',
    base_units           integer,
    bonus_units          integer default 0,
    effective_units      integer,
    effective_unit_price numeric(14, 4),
    price_type           text not null default 'public_listed_price',
    matched              boolean not null default false,
    scrape_status        text not null check (scrape_status in ('success', 'failed')),
    error_message        text,
    parser_method        text,
    parser_confidence    numeric(4, 3),
    source_url           text,
    captured_at          timestamptz not null default now()
);

create index if not exists idx_price_logs_sku_time
    on public.price_logs (sku_id, captured_at desc);
create index if not exists idx_price_logs_mapping_time
    on public.price_logs (mapping_id, captured_at desc);
create index if not exists idx_price_logs_game_time
    on public.price_logs (game_id, captured_at desc);

-- ---------------------------------------------------------------------------
-- undercut_alert_states: notification deduplication. An alert fires only on
-- the transition NOT undercutting -> undercutting (threshold 10%).
-- ---------------------------------------------------------------------------
create table if not exists public.undercut_alert_states (
    id               bigint generated by default as identity primary key,
    sku_id           bigint not null references public.game_skus(id) on delete cascade,
    source_id        bigint not null references public.sources(id) on delete cascade,
    is_undercutting  boolean not null default false,
    undercut_pct     numeric(6, 2),
    last_alerted_at  timestamptz,
    updated_at       timestamptz not null default now(),
    unique (sku_id, source_id)
);

-- ---------------------------------------------------------------------------
-- scrape_runs: workflow-level health / run summaries.
-- ---------------------------------------------------------------------------
create table if not exists public.scrape_runs (
    id              bigint generated by default as identity primary key,
    started_at      timestamptz not null default now(),
    finished_at     timestamptz,
    status          text not null default 'running' check (status in ('running', 'success', 'partial', 'failed')),
    sources_total   integer default 0,
    sources_success integer default 0,
    sources_failed  integer default 0,
    alerts_sent     integer default 0,
    notes           text
);

-- ---------------------------------------------------------------------------
-- Views (security_invoker = true so underlying RLS still applies)
-- ---------------------------------------------------------------------------
create or replace view public.latest_price_logs
with (security_invoker = true) as
select distinct on (coalesce(mapping_id::text, 'dana-' || sku_id::text))
    *
from public.price_logs
where mapping_id is not null
   or (source_id in (select id from public.sources where source_type = 'dana')
       and sku_id is not null)
order by coalesce(mapping_id::text, 'dana-' || sku_id::text),
         captured_at desc,
         id desc;

create or replace view public.latest_dana_prices
with (security_invoker = true) as
select distinct on (p.sku_id)
    p.*
from public.price_logs p
join public.sources s on s.id = p.source_id
where s.source_type = 'dana'
  and p.scrape_status = 'success'
  and p.sku_id is not null
order by p.sku_id, p.captured_at desc, p.id desc;

create or replace view public.unmatched_products
with (security_invoker = true) as
select p.*
from public.price_logs p
join public.sources s on s.id = p.source_id
where s.source_type = 'competitor'
  and p.scrape_status = 'success'
  and p.matched = false
  and p.sku_id is null;

-- ---------------------------------------------------------------------------
-- updated_at triggers
-- ---------------------------------------------------------------------------
drop trigger if exists trg_games_updated_at on public.games;
create trigger trg_games_updated_at before update on public.games
    for each row execute function public.set_updated_at();

drop trigger if exists trg_skus_updated_at on public.game_skus;
create trigger trg_skus_updated_at before update on public.game_skus
    for each row execute function public.set_updated_at();

drop trigger if exists trg_sources_updated_at on public.sources;
create trigger trg_sources_updated_at before update on public.sources
    for each row execute function public.set_updated_at();

drop trigger if exists trg_mappings_updated_at on public.source_sku_mappings;
create trigger trg_mappings_updated_at before update on public.source_sku_mappings
    for each row execute function public.set_updated_at();

drop trigger if exists trg_alert_states_updated_at on public.undercut_alert_states;
create trigger trg_alert_states_updated_at before update on public.undercut_alert_states
    for each row execute function public.set_updated_at();

-- ============================================================================
-- Grants + Row Level Security
-- ============================================================================

-- user_profiles
alter table public.user_profiles enable row level security;
revoke all on public.user_profiles from anon;
grant select on public.user_profiles to authenticated;

create policy "users read own profile"
    on public.user_profiles for select
    to authenticated
    using (id = auth.uid() or public.is_admin());

create policy "admins insert profiles"
    on public.user_profiles for insert
    to authenticated
    with check (public.is_admin());

create policy "admins update profiles"
    on public.user_profiles for update
    to authenticated
    using (public.is_admin())
    with check (public.is_admin());

create policy "admins delete profiles"
    on public.user_profiles for delete
    to authenticated
    using (public.is_admin());

-- games
alter table public.games enable row level security;
revoke all on public.games from anon;
grant select on public.games to authenticated;
grant insert, update, delete on public.games to authenticated;

create policy "authenticated read games"
    on public.games for select to authenticated using (true);
create policy "admins insert games"
    on public.games for insert to authenticated with check (public.is_admin());
create policy "admins update games"
    on public.games for update to authenticated
    using (public.is_admin()) with check (public.is_admin());
create policy "admins delete games"
    on public.games for delete to authenticated using (public.is_admin());

-- game_skus
alter table public.game_skus enable row level security;
revoke all on public.game_skus from anon;
grant select on public.game_skus to authenticated;
grant insert, update, delete on public.game_skus to authenticated;

create policy "authenticated read skus"
    on public.game_skus for select to authenticated using (true);
create policy "admins insert skus"
    on public.game_skus for insert to authenticated with check (public.is_admin());
create policy "admins update skus"
    on public.game_skus for update to authenticated
    using (public.is_admin()) with check (public.is_admin());
create policy "admins delete skus"
    on public.game_skus for delete to authenticated using (public.is_admin());

-- sources
alter table public.sources enable row level security;
revoke all on public.sources from anon;
grant select on public.sources to authenticated;
grant insert, update, delete on public.sources to authenticated;

create policy "authenticated read sources"
    on public.sources for select to authenticated using (true);
create policy "admins insert sources"
    on public.sources for insert to authenticated with check (public.is_admin());
create policy "admins update sources"
    on public.sources for update to authenticated
    using (public.is_admin()) with check (public.is_admin());
create policy "admins delete sources"
    on public.sources for delete to authenticated using (public.is_admin());

-- source_sku_mappings
alter table public.source_sku_mappings enable row level security;
revoke all on public.source_sku_mappings from anon;
grant select on public.source_sku_mappings to authenticated;
grant insert, update, delete on public.source_sku_mappings to authenticated;

create policy "authenticated read mappings"
    on public.source_sku_mappings for select to authenticated using (true);
create policy "admins insert mappings"
    on public.source_sku_mappings for insert to authenticated with check (public.is_admin());
create policy "admins update mappings"
    on public.source_sku_mappings for update to authenticated
    using (public.is_admin()) with check (public.is_admin());
create policy "admins delete mappings"
    on public.source_sku_mappings for delete to authenticated using (public.is_admin());

-- price_logs (read-only from the dashboard)
alter table public.price_logs enable row level security;
revoke all on public.price_logs from anon;
grant select on public.price_logs to authenticated;

create policy "authenticated read price logs"
    on public.price_logs for select to authenticated using (true);

-- undercut_alert_states (read-only from the dashboard)
alter table public.undercut_alert_states enable row level security;
revoke all on public.undercut_alert_states from anon;
grant select on public.undercut_alert_states to authenticated;

create policy "authenticated read alert states"
    on public.undercut_alert_states for select to authenticated using (true);

-- scrape_runs (read-only from the dashboard)
alter table public.scrape_runs enable row level security;
revoke all on public.scrape_runs from anon;
grant select on public.scrape_runs to authenticated;

create policy "authenticated read scrape runs"
    on public.scrape_runs for select to authenticated using (true);

-- views
revoke all on public.latest_price_logs from anon;
revoke all on public.latest_dana_prices from anon;
revoke all on public.unmatched_products from anon;
grant select on public.latest_price_logs to authenticated;
grant select on public.latest_dana_prices to authenticated;
grant select on public.unmatched_products to authenticated;
